version: '3.5'

networks:
  streams_footprint: {}

services:

  app1:
    image: app1allt6
    hostname: app1
    container_name: app1
    networks:
      - streams_footprint
    environment:
      - PARAM_KAFKA=kafka:9092

  app2:
    image: app2
    hostname: app2
    container_name: app2
    networks:
      - streams_footprint
    environment:
      - PARAM_KAFKA=kafka:9092

  footprinter:
    image: footprinter
    hostname: footprinter
    container_name: footprinter
    networks:
      - streams_footprint
    environment:
      - PARAM_KAFKA=kafka:9092
      - PRAM_ELASTICSEARCH=elasticsearch:9200

  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    hostname: zookeeper
    container_name: zookeeper
    networks:
      - streams_footprint
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - ./data/zookeeper/data:/data
      - ./data/zookeeper/datalog:/datalog

  kafka:
    image: confluentinc/cp-kafka:6.2.0
    hostname: kafka
    container_name: kafka
    networks:
      - streams_footprint
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    volumes:
      - ./data/kafka:/data
    depends_on:
      - zookeeper

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    hostname: elasticsearch
    container_name: elasticsearch
    networks:
      - streams_footprint
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/elaticsearch:/usr/share/elasticsearch/data
